on:
  push:
  # schedule:
  #   - cron: "*/30 * * * *"
jobs:
  hello_world_job:
    runs-on: self-hosted
    name: Run treebeard
    steps:
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      - uses: aws-actions/amazon-ecr-login@v1
        id: login-ecr
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8.3
      - run: printenv
      - uses: treebeardtech/treebeard@master
        with:
          api-key: ${{ secrets.TREEBEARD_API_KEY }}
          docker-registry: "${{ steps.login-ecr.outputs.registry }}"
