on:
  push:
  schedule:
    - cron: "*/59 * * * *"
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Run treebeard
    steps:
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      - uses: aws-actions/amazon-ecr-login@v1
        id: login-ecr
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Run
        run: |
          pip install git+https://github.com/treebeardtech/treebeard.git@local-docker#subdirectory=treebeard-lib
          treebeard configure --api_key ${{ secrets.TREEBEARD_API_KEY }} --project_id "$GITHUB_REPOSITORY_OWNER"
          export DOCKER_REGISTRY=${{ steps.login-ecr.outputs.registry }}
          treebeard run --confirm --dockerless --upload
          treebeard run --confirm
