on:
  push:
  schedule:
    - cron: "*/59 * * * *"
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Run treebeard
    steps:
      - name: Run
        uses: treebeardtech/treebeard@local-docker
        with:
          api-key: ${{ secrets.TREEBEARD_API_KEY }}
          notebooks: "run_on_schedule.ipynb"
        env:
          DOCKER_REGISTRY: 524997937988.dkr.ecr.eu-central-1.amazonaws.com
          DOCKER_LOGIN: AWS
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
