on:
  push:
  schedule:
    - cron: "*/30 * * * *"
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Run treebeard
    steps:
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      - uses: aws-actions/amazon-ecr-login@v1
        id: login-ecr
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - run: gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin
      - run: docker pull gcr.io/treebeard-259315/ipywidgets
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: printenv
      - uses: treebeardtech/treebeard@local-docker
        with:
          api-key: ${{ secrets.TREEBEARD_API_KEY }}
          docker-registry: "${{ steps.login-ecr.outputs.registry }}"
